### ISSUE TITLE
Desjardins Credit Card

### ISSUE THREAD

**Issue by YurkoWasHere** [hyphacoop/organizing#134] opened 2019-10-21 13:07 UTC
Re-ticketed from #

## Shared Description

:speaking_head: **Loomio:** N/A  
:date: **Due date:** N/A  
:dart: **Success criteria:** Have a credit card for org to easily pay bills with.

## To Do

- [x] Do we need a Visa
- [x] Review requirements for Visa Card
  - [x] Decide if its worth it for $60 / year (decided to build credit that it was important)
- [x] Decide on how many/who to issue card to (2 cards, @YurkoWasHere and @dcwalk )
- [x] Apply for the card
- [x] create calendar event to reapply Fri, Jul 31, 2020 (1 year birthday!)
- [x] get on the waitlist for TransferWise Mastercard in Canada https://github.com/hyphacoop/organizing/issues/134#issuecomment-561313289 -- patcon
- [x] @dcwalk followup with Business Centre Toronto RE: [Business Freedom Solutions package](https://www.desjardins.com/ca/business/financing-credit/credit-cards/business-freedom-solutions/index.jsp) (1 year of records still applies)
- [x] Decide on process of paying/reconciling visa card expenses (Process of submitting receipts etc)
- [x] Receive card
- [x] Apply for CC
- [x] bump card limit https://github.com/hyphacoop/organizing/issues/134#issuecomment-701657441
- [x] Switch all recurring payments to CC
  - [x] ben's stuff
  - [x] cwcf etc -- @dcwalk 
- [x] Sync with QB
- ~~make rules to auto-match payments into appropriate accounts (e.g. OVH, DO, etc.)~~ (edit: happen over time)
- [x] Make Cost Centre in member expense sheet match with our Chart of Accounts

**Comment by YurkoWasHere** [comment] 2019-10-21 13:12
## Links/Notes 

A way to pay your business expenses that includes:  
- a credit card specially designed for the needs of businesses1, 
- accord D Business FINANCING, for either a term loan from your caisse or Corporate Financial Centre, or to finance the purchase of durable goods at participating merchants.


https://www.desjardins.com/en/services_en_ligne/accesd_affaires/fiches_produits/fp_cartes_fiche_produit_ca.jsp

---

## Application Process

(Info from the Online Account **NOTE** Cant be applied for online due to multi-owner/NPO)

Before completing your application, take a few minutes to read the following information:

- Allow approximately 30 minutes to complete your application.
- You can verify and modify your responses before submitting the application.
- We suggest that you print your application form before submitting it.

Have the information you will need to provide on hand:

- The company cardholders' first and last names, dates of birth, addresses, telephone numbers and functions.
- The owner's gross monthly income (before taxes);
- The owner's monthly rent/mortgage;
- The owner's current employer(s);
- The owner's properties, investments and savings;
- The monthly payments and balances of the owner's credit cards, lines of credit, personal loans and mortgages (including property taxes); car lease payments and other financial commitments (interest-free financing, pay in one year, etc.);
- General information about the company (address, date company was established)
- The company's business registration number.
- General information about the owner (personal address, social insurance number)
- Financial information about the company (for financing equal to or over $35,000).

Important: It is your responsibility to review the accuracy of the personal information (assets and liabilities).
 
Please note that all our forms are secure and that the personal  information you send is used only for the purpose of responding to your  application. To find out more about Privacy and Security
 
For assistance while completing your application, call an AccèsD Affaires financing products sales agent at 1 888 233-2473.

---
## Cant be done online for us

> If the company is owned by more than one person or has more than one administrator or if you are a non-profit organization (NPO), please apply at your caisse or at your Desjardins Business Centres.

## Questions asked

### Business card credit limit:

The Business card is a great way to pay for or finance the purchase of goods and services and effectively manage your business expenses. The VISA Desjardins Business Card entitles you to the following:

- The VISA Desjardins Business Savings Program, offering a 1% rebate on card purchases above $12,000 to a maximum of $500,000 per year, per company. The rebate is credited to your business account on the account anniversary date.
-  Accord D Business financing.
-  Interest rate equivalent to the Business Freedom Solutions line of credit interest rate.
-  Cash advances, available at Desjardins caisses, VISA financial institutions, and Interac VISA and caisse ATMs.
-  Ability to request additional cards.
-  Travel assistance.
-  Liability insurance against use of card after termination of employment.
-  VISA Desjardins à la carte Ticket Service.
-  Emergency cash up to $1,000.

###  Accord D Business financing credit limit 

The maximum Accord D Business financing credit limit is $100,000.

Accord D Business financing is a second credit limit separate from your Business card credit limit that lets your company obtain instalment financing.

You have two options:

- Financing in the form of a cash loan, directly from your caisse or Financial Corporate Centre, at the lowest market rates, and that automatically includes life and critical illness insurance at no extra charge for the business owner(s)1;
- Financing from over 350 Canadian retailers at interest rates that are lower than those on your Business card.

Insurance coverage underwritten by Desjardins Financial Security Life Assurance Company. Only the insurance certificate sent with the statement of account is admissible for resolution purposes. Some conditions and restrictions apply.

**Comment by benhylau** [comment] 2019-10-22 19:05
I think a credit card isn't absolutely necessary if we do pay personally and reimburse model on expenses, but I would be in favour of us getting a shared CC

**Comment by YurkoWasHere** [comment] 2019-10-31 14:33
Dejardins Visa cost - $60.00 / year for first card $0.00 for subsequent

Requires Personal Credit Check + Company Credit Check - Depends on the credit limit

Suggestions credit limit: 
Total number of expenses per month x 2 months (because you have 3 weeks from the bill date to pay, until)

Must be done over the phone.

**Comment by patcon** [comment] 2019-10-31 19:42
So it's a corp card, but they aren't intended to be "general use" -- they have one person's name (against which credit check is run), and only _that_ person should be using it?

Sorry, I'm new to this.

**Comment by patcon** [comment] 2019-10-31 19:48
Also, @uditvira raised in our call yesterday that CC seemed really helpful to have early.

Lastly, if I'm understanding correctly that we just need one card for now, whose name could/should it be in? And will that person assist others in making purchases, so we can just have one card for now?

Thanks Yurko!

**Comment by YurkoWasHere** [comment] 2019-10-31 20:17
So credit cards ALWAYS have a name on it
Business cards look like

```
                  5149-xxx-xxx-xxx-xxxx-xx

COMPANY NAME
NAME OF USER
```

But when making online payments you use the NAME OF USER not COMPANY NAME as "name on card"

"terms of use" of credit card is named person on the card only and numbers are not to be shared.  

Even when you add some one to your personal account  ( like your kid ) that are issued a separate card with a separate number even though its not their credit being used.

Same with the "TAP" credit cards on your phone. It's a different number on there too.

In reality this is not always followed but its at the risk of the named party. If their card is compromised its on them to have to answer to it.

**Comment by YurkoWasHere** [comment] 2019-10-31 20:17
I should point out that the other option is to just expense things...

**Comment by benhylau** [comment] 2019-10-31 21:39
What @YurkoWasHere said re: CC is consistent with my knowledge. CCs are tied to people, and that person decides if they will pay for collective expenses thru it. @YurkoWasHere and I talked on chat to decide he'll get it, not me.

**Comment by patcon** [comment] 2019-10-31 22:46
If we just have one person to be holder, I'd make preferential nomination of @dcwalk (if she is willing), just to avoid unforeseen privacy concerns yurko might have (which I don't fault you for, but would like to navigate around)

**Comment by YurkoWasHere** [comment] 2019-11-01 02:31
### Clarification questions

[link to card info online](https://www.desjardins.com/ca/business/financing-credit/credit-cards/index.jsp#our-visa-desjardins-cards)

- [ ] First card is $60.00
- [ ] Subsequent Cards are free 
   - [ ]Unlimited subsequent cards 
- [ ] Chashback 1% AFTER $1500.00 
- [ ]  Corporate vs Business card -  whats the difference
- [ ] Where do the cards get delivered to

**Comment by dcwalk** [comment] 2019-11-13 21:36
We discussed at the Nov 06 all hands and those present agreed to the following:

- Proposal: we apply for $1000 ($60) credit card with Desjardins with two people listed on it: @YurkoWasHere Yurko, @dcwalk 
   - recommendation: 2 mths of expenses
   - application for: $500 - 1000
        - Consensed on call, all 5 members okay with this proposal

**Comment by patcon** [comment] 2019-11-20 17:09
@benhylau called and found credit card was declined because we need one year of history first. [chat context.](https://matrix.to/#/!JloFJtoONurMdgcZCa:tomesh.net/$15741999221802PIHzi:tomesh.net?via=tomesh.net&via=elon.li) anything else ben?

created #todo to revisit

**Comment by benhylau** [comment] 2019-11-21 17:59
No, that's pretty much it, and there seems to be a 1% cash back zero annual fee card.

**Comment by patcon** [comment] 2019-11-21 20:39
https://www.desjardins.com/ca/personal/loans-credit/prepaid-card/index.jsp

> **Additional card**  
> Get an additional card (annual fee: $4.95/ card) for your spouse or children.

- [ ] @YurkoWasHere legally adopt fellow Hypha directors
- [ ] order 3 additional cards

**Comment by patcon** [comment] 2019-12-03 19:11
Turns out transferwise has a Mastercard debit card for business accounts:
https://transferwise.com/help/18/transferwise-debit-mastercard/2935775/can-i-get-a-transferwise-debit-mastercard-for-my-business

Not yet available in Canada, but I signed up f******@hypha.coop onto the waitlist via this form :)
https://www.research.net/r/cardwaitlist

> Thanks! You're on the list. 
> Open your borderless account now, to make sure you're at the head of the line.
>
> We'll send you an email as soon as you can order a debit card.

**Comment by dcwalk** [comment] 2019-12-04 19:34
Had a very helpful chat with Desjardins folks RE: Business Freedom Solutions package, which is the combined Credit Card and Line of Credit (As well as Business Financing stuff): https://www.desjardins.com/ca/business/financing-credit/credit-cards/business-freedom-solutions/index.jsp

Was super straightforward about conditions for application and said it'll still require the year of history.

**Comment by benhylau** [comment] 2020-02-20 18:09
Wait until one-year and get a personal credit card that is associated with Hypha.

**Comment by benhylau** [comment] 2020-09-04 17:32
After talking with Rodica, moving most expenses to CC will save us and her a lot of time. Currently she references our spreadsheet and manually sort stuff into QB. Adding the following to top post:
- Apply for CC
- Switch all recurring payments to CC
- Sync with QB and make rules to auto-match payments into appropriate accounts (e.g. OVH, DO, etc.)
- Make Cost Centre in member expense sheet match with our Chart of Accounts

**Comment by YurkoWasHere** [comment] 2020-09-22 19:05
Applied for corporate credit card.

Timeline: preferably <1 week no more then 30 days from today

- General Resolution sign [VISA  - General resolution.pdf](https://github.com/hyphacoop/organizing/files/5263490/VISA.-.General.resolution.pdf)
- 1st year financials

Submit via email:
> Please send us the completed and signed form by email at credit.commercial.form@scd.desjardins.com or by fax at 514-397-9852 or 1-866-720-4210 (toll free). We’ll process your request as quickly as possible.

**Comment by YurkoWasHere** [comment] 2020-09-30 21:23
We got the card, 
we just dont have the card.
(waiting for mail man)

**Comment by patcon** [comment] 2020-09-30 21:30
@benhylau suggests upping limit to allow ARIN/ASN payment

**Comment by patcon** [comment] 2020-10-28 21:33
dicsussed in allhands today

**Comment by YurkoWasHere** [comment] 2020-10-29 16:21
Called in - Credit limit increased to $4,000 (instead of $3,000)

**Comment by benhylau** [comment] 2020-11-03 21:37
Talked with @dcwalk the cwcf isn't on auto, so she will use new card when invoice comes. I checked it off.

**Comment by dcwalk** [comment] 2020-11-06 19:58
recent call with them confirmed they moved to an online process for renewal and that should happen post-AGM. They'll generate an invoice to send and we should be able to pay with CC. So not a block on closing this issue

**Closed** 2020-11-25 22:19 UTC
Labels: [priority-★★★], wg:finance
