### ISSUE TITLE
Seek clarity on HST status

### ISSUE THREAD

**Issue by patcon** [hyphacoop/organizing#120] opened 2019-10-03 22:03 UTC
Re-ticketed from https://github.com/hyphacoop/organizing/issues/70#issuecomment-538146143 and 

## Shared Description

:speaking_head: **Loomio:** N/A  
:date: **Due date:** N/A  
:dart: **Success criteria:** We have a shared understanding with our accountant about when we're charging HST.  

Arose from accountant kick-off meeting. [notes.](https://github.com/hyphacoop/organizing-private/blob/master/meeting-notes/2019-10-01-accountant-kickoff.md)

## To Do

- [x] send our accountant details on mission-related work and HST
    - [ ] ~~review _OCA Guide to the Act_ for relevant bits to pass~~ _(edit: bl doesn't know what this means)_
    - [x] Track accountant's determination from CRA
- [x] research HST recovery for non-profits
- [x] pass information to accountant about prior CRA guidance related to non-profit worker co-op and grants. (for her to look up, if possible)
  - Re: [External accounting consultant SM's](http://www.sallyemiller.com/) request on behalf of [Local Food and Farm Co-op](http://cultivatingfoodcoops.net/). See https://github.com/hyphacoop/organizing/issues/120#issuecomment-557810167.
- [x] confirm understanding of zero-rated for international HST, re: https://github.com/hyphacoop/organizing/issues/120#issuecomment-557512162
  - ~~canadian web dev shop~~ _(edit: not necessary)_
  - [x] our accountant
- [x] ~~use accrual method of accounting, and set up to remit taxes based on invoices (not collected cash)~~ _(edit: bl: we are going to do cash based on April 23, 2020 discussion)_
- [x] add scenarios to handbook https://github.com/hyphacoop/organizing/issues/120#issuecomment-611993846

**Comment by benhylau** [comment] 2019-11-22 12:21
_Moved here from https://github.com/hyphacoop/organizing/issues/154_

---

Thanks @YurkoWasHere the "non-profit organization promoting the arts in your local community in Nova Scotia" example is very helpful. Basically we'd charge HST for everything except mission-aligned initiatives (e.g. workshops), and we are eligible to claim _Input Tax Credit (ITC)_ on expenditures not relating to already exempt activities.

## International Clients

For international clients, it seems we do not need to collect HST on most of our digitally-offered services (e.g. software development, devops, design) because it is classified as _exported goods and services_, which is zero-rated. This means we can also collect ITC on related expenditures, since _zero-rated_ is not the same as _exempt_. See: [Intangible personal property](https://www.canada.ca/en/revenue-agency/services/forms-publications/publications/b-090/gst-hst-electronic-commerce.html#P22_9331) and [Excise Tax Act section 10 of Part V of Schedule VI](https://laws-lois.justice.gc.ca/eng/acts/E-15/page-179.html#h-201391). The latter text reproduced below:

```
10 A supply of an invention, patent, trade secret, trademark, trade-name, copyright, industrial design or other intellectual property or any right, licence or privilege to use any such property, where the recipient is a non-resident person who is not registered under Subdivision D of Division V of Part IX of the Act at the time the supply is made.

10.1 A supply of intangible personal property made to a non-resident person who is not registered under Subdivision D of Division V of Part IX of the Act at the time the supply is made, but not including

    (a) a supply made to an individual unless the individual is outside Canada at that time;

    (b) a supply of intangible personal property that relates to

        (i) real property situated in Canada,

        (ii) tangible personal property ordinarily situated in Canada, or

        (iii) a service the supply of which is made in Canada and is not a zero-rated supply described by any section of this Part or Part VII or IX;

    (c) a supply that is the making available of a telecommunications facility that is intangible personal property for use in providing a service described in paragraph (a) of the definition telecommunication service in subsection 123(1) of the Act;

    (d) a supply of intangible personal property that may only be used in Canada; or

    (e) a prescribed supply.
```

My read is that these activities are intellectual property exports made in Canada, which are zero-rated for the purpose of HST collection.

More accessible but unofficial references below:

- http://vhaccounting.ca/2019/03/08/gst-hst-on-remote-services/
- https://www.reddit.com/r/PersonalFinanceCanada/comments/5uwjkw/do_i_have_to_charge_my_american_clients_gstpst/

**Comment by patcon** [comment] 2019-11-23 16:05
Aligns with what's Matt @ 4P told me via email (and I've perhaps not been stating clearly enough in convo):

@patcon wrote:

> Hopefully a quick one:
>
> Conflicting info from two accountants we're vetting: One says don't charge clients HST, the other says that HST is based on service type, and web development service should have it added.
>
> **Do you charge HST on services rendered as nonprofit builder?**

Response:

> there are things that we charge HST for and those that we don't - so service type. I checked with my partner whose non-profit was just audited and she said 100% you have to charge HST on some items (a contract yes, services under a grant maybe no). In fact they had to get a ruling from CRA on a specific grant and whether they needed to have had charged HST for one part of it. I strongly suspect you need to charge HST for web development. A workshop on how to do web development for the public good? Maybe not.  The thing is that non-profits can recover some HST.

**Comment by patcon** [comment] 2019-11-24 20:17
Another unofficial doc supporting the fact that international software dev (when product not serving Canadians) being zero-rated:

[Inside Formstack: Working Remotely for an American Company as a Canadian](https://medium.com/inside-formstack/working-remotely-for-an-american-company-as-a-canadian-e96296eea477)

> If you’re a Canadian working for an American company, your services may be what they call zero-rated. This applies to services and intellectual property that is **exported outside Canada and is not generally consumed, used, or enjoyed in Canada**. In my case, I do product design where the work is saved on servers outside Canada, where the product is delivered to a US company who sells the services from the US. This type of work IS zero-rated. Here are the CRA zero-rated documents for reference and CRA electronic commerce reference. It would be a good idea to **reference those above documents in your invoices** just in case the CRA questions you about not charging HST.

(Aside: The above article also seems great for working with **international contractors**, should we ever wish to.)

**Comment by patcon** [comment] 2019-11-25 17:56
I spent a few minutes making my understanding into a visual flow-chart. This worth playing with as a scratch space to ensure we're all on the same page for how we plan to charge taxes and get refunds?
https://docs.google.com/drawings/d/1w1IYv9eNJ3lEC4cPWwNunKITD0pe6yRv1MTPluTnDcQ/edit

Still prob needs to have something about "grants", and also, something about ITC.

Please feel free to edit it liberally, if you'd like

**Comment by patcon** [comment] 2019-11-25 18:03
Added a todo for international invoices. Look ok?

**Comment by patcon** [comment] 2020-01-08 21:11
Blocked on spending money for expert opinion. Next step should just be talking to expert.

**Comment by patcon** [comment] 2020-02-20 17:57
Related to accrual vs cash decision, but no action: https://github.com/hyphacoop/organizing/issues/154#issuecomment-589221165

**Comment by dcwalk** [comment] 2020-03-11 13:52
discussion in gov meeting, not our area, dropping our tag.

**Comment by benhylau** [comment] 2020-04-10 10:38
We are a _non-profit organizations_ and this [GST/HST Information for Non-Profit Organizations](https://www.canada.ca/en/revenue-agency/services/forms-publications/publications/rc4081/gst-hst-information-non-profit-organizations.html#qmothnpo) applies to us for tax purposes. Here are the sections as they apply to us:

- https://www.canada.ca/en/revenue-agency/services/forms-publications/publications/rc4081/gst-hst-information-non-profit-organizations.html#P245_16179
  >A non-profit organization is a small supplier if the total amount of all revenues (before expenses) from the worldwide taxable supplies of all of the organization's activities and those of its associates, is $50,000 or less in any single calendar quarter and in the last four consecutive calendar quarters.
  >
  >If you are under the threshold amount in one calendar quarter, but you are over the threshold during four (or fewer) consecutive calendar quarters, you are considered to be a small supplier for those calendar quarters and a month following those quarters. Your effective date of registration would be the day the first supply was made after you cease being a small supplier. You have 29 days from this day to register for the GST/HST.
- We can **claim ITCs** for the GST/HST paid or payable on purchases made and expenses incurred to provide **exported property and services** https://www.canada.ca/en/revenue-agency/services/forms-publications/publications/rc4081/gst-hst-information-non-profit-organizations.html#P210_12901
  >Some supplies are zero‑rated under the GST/HST – that is, GST/HST applies at a rate of 0%. This means that you do not charge GST/HST on these supplies, but you may be eligible to claim ITCs for the GST/HST paid or payable on purchases made and expenses incurred to provide these supplies.
- Exemptions for certain supplies https://www.canada.ca/en/revenue-agency/services/forms-publications/publications/rc4081/gst-hst-information-non-profit-organizations.html#xmptfnpr these are very specific and often times case-by-case, the section that will likely apply to us is https://www.canada.ca/en/revenue-agency/services/forms-publications/publications/rc4081/gst-hst-information-non-profit-organizations.html#P343_32830 (see (**Grants and subsidies** and **Sponsorships**)
- **Input tax credits (ITCs)** https://www.canada.ca/en/revenue-agency/services/forms-publications/publications/rc4081/gst-hst-information-non-profit-organizations.html#P362_35730 is a complex subject and should be handled by our Accountant
  >As a non-profit organization that is a GST/HST registrant, you recover the GST/HST paid or payable on the purchases and expenses related to your commercial activities by claiming an ITC.
  - We are eligible to use the **Simplified method for claiming ITCs** https://www.canada.ca/en/revenue-agency/services/forms-publications/publications/rc4081/gst-hst-information-non-profit-organizations.html#P507_48832
    >When you use the simplified method for claiming ITCs, you do not have to show the GST/HST separately in your records. Instead, **total the amount of your taxable purchases for which you can claim an ITC**. You still have to keep the usual documents to support your ITC claims in case we ask to see them.
- **Simplified accounting methods** https://www.canada.ca/en/revenue-agency/services/forms-publications/publications/rc4081/gst-hst-information-non-profit-organizations.html#P654_63852
  - We should be eligible for the **special quick method**
    >This special quick method reduces paperwork and makes it easier to calculate the GST/HST remittances and file GST/HST returns because it eliminates the need to keep track of the actual GST/HST paid on purchases, or to separate purchases that are for commercial activities versus those for making exempt supplies.
    >
    >When you use the special quick method, you still collect the GST/HST on the property or services you supply. However, to calculate the amount of the GST/HST to be remitted, multiply the amount of your GST/HST included supplies for the reporting period by the remittance rate, or rates, that apply in your situation.
    >
    >The special quick method remittance rates are less than the applicable rate of tax that you collect. This means that you remit only part of the tax you collect. Since you cannot claim input tax credits (ITCs) on most of your purchases when you use this method, the part of the tax that you keep accounts for the approximate value of the ITCs you would normally have claimed. You can claim ITCs on certain items only.
  - Rates https://www.canada.ca/en/revenue-agency/services/forms-publications/publications/rc4058/quick-method-accounting-gst-hst.html

**Comment by benhylau** [comment] 2020-04-10 11:36
Clarify the following scenarios with our Accountant and add as concrete examples to handbook that are relevant to our business activities, once we are no longer a small supplier:

1. We provide IT consultation and software development service to a Canadian client and subcontracts a Canadian web developer, spends $100 on web hosting and $1,000 on a laptop to help us fulfill the contract.
    - We will charge **13% HST** when invoicing the client
    - The Canadian subcontractor will charge us 13% HST when invoicing us
    - We are eligible to reclaim the 13% HST paid to the subcontractor through ITC claim
    - We are eligible to reclaim the 13% HST of $100 paid to acquire web hosting through ITC claim
    - We are eligible to reclaim the 13% HST of $1,000 paid to acquire the laptop through ITC claim

2. In the same scenario, but the client is a non-Canadian company.
    - We will charge no HST when invoicing the client, and mark as _Intellectual property exports, zero-rated_ on invoice
    - The Canadian subcontractor will charge us 13% HST when invoicing us
    - We are still eligible for all ITC claims

3. In the same scenario, but the subcontractor is a non-resident of Canada and the service is rendered outside the country.
    - The foreign subcontractor will not charge us HST when invoicing us
    - There is no ITC claim on the payment to our subcontractor
    - We are still eligible for all _other_ ITC claims

4. We receive a grant from a private company to facilitate a free digital security workshop that is open to public, and we spent $100 on materials.
    - HST does not apply, and we do not need to collect or remit HST on the grant amount
    - The $100 materials is not eligible for ITC claims because the grant is HST exempt (not zero-rated)

5. We receive the same "grant" amount but the workshop has a registration fee, collected by the client, and is not open to public.
    - We need to charge **13% HST** when invoicing the client, this is no longer a grant
    - The $100 materials is eligible for ITC claims

**Comment by benhylau** [comment] 2020-04-21 16:59
>https://github.com/hyphacoop/organizing/issues/120#issuecomment-611993846

@dcwalk we have confirmation from our accountant that this is correct, do you think handbook/guides is the right place for this?

**Comment by benhylau** [comment] 2020-04-21 17:05
>use accrual method of accounting, and set up to remit taxes based on invoices (not collected cash)

@YurkoWasHere anything needs to be done for this? I want to close this one out asap as it's blocking two other issues that are also kinda urgent.

**Comment by dcwalk** [comment] 2020-04-21 17:10
> > [#120 (comment)](https://github.com/hyphacoop/organizing/issues/120#issuecomment-611993846)
> 
> @dcwalk we have confirmation from our accountant that this is correct, do you think handbook/guides is the right place for this?

Sounds good to me! I'd say take care of this how you all in Finance WG need to, but that we should pull out a concise sentence after that to add to #155 and link to the Finance section?

**Comment by benhylau** [comment] 2020-04-22 18:46
This has accountant recommendations about ITCs https://meetings.hypha.coop/2020-04-22-call-with-accountant.html which is pretty clear that we should do conventional method (not quick).

**Comment by benhylau** [comment] 2020-04-27 11:43
We can close this once the PR merges.

**Closed** 2020-04-28 16:29 UTC
Labels: [priority-★★☆], wg:finance
